spring:
  datasource:
    url: jdbc:postgresql://dpg-d111fcadbo4c739i8hhg-a.oregon-postgres.render.com/tradetown
    username: anand
    password: TKPqignIe7ZS0ygFFMQuK4yE4NOa7wAH

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: adisingh234560@gmail.com
    password: mwvb iecu vrea rpis
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 5m
