spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tradetown
    username: root
    password: Anand567@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: adisingh234560@gmail.com
    password: mwvb iecu vrea rpis
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 1m
